using EpubReader.Controller;
using EpubReader.Model;
using System.Linq;
using System.Security;
using System.Windows;
using System.Windows.Controls;


namespace EpubReader.View
{
    /// <summary>
    /// Lógica de interacción para Start.xaml
    /// </summary>
    public partial class Start : Window
    {
        public Start()
        {
            InitializeComponent();
            LoadBooks();
        }
        private void LoadBooks()
        {
            BooksBinding.ItemsSource = BookController.GetBooks();
            BooksBinding.MaxColumnWidth = 100;
            BooksBinding.CanUserResizeColumns = true;
            BooksBinding.AutoGeneratedColumns += (s, e) =>
            {
                DataGridColumn? idColumn = BooksBinding.Columns.FirstOrDefault(c => c.Header.ToString() == "Id");
                int idIndex = BooksBinding.Columns.IndexOf(idColumn);
                BooksBinding.Columns[idIndex].Visibility = Visibility.Hidden;

                DataGridColumn? uniqueIdColumn = BooksBinding.Columns.FirstOrDefault(c => c.Header.ToString() == "UniqueId");
                int uniqueIdIndex = BooksBinding.Columns.IndexOf(uniqueIdColumn);
                BooksBinding.Columns[uniqueIdIndex].Visibility = Visibility.Hidden;
            };
        }

        private void AddBookButton(object sender, RoutedEventArgs e)
        {
            Microsoft.Win32.OpenFileDialog dialog = new ()
            {
                FileName = "Select epub file",
                Filter = "ePub files (*.epub)|*.epub|All files (*.*)|*.*",
                Title = "Open ePub File"
            };
            if (dialog.ShowDialog() == true)
            {
                try
                {
                    string bookName = dialog.SafeFileName;
                    string safeFileName = dialog.SafeFileName;

                    string filePathOld = dialog.FileName;

                    Book? newBook = FileController.ObtainBookData(filePathOld);
                    if (newBook == null)
                    {
                        Console.WriteLine("Error obtaining book data");
                        return;
                    }
                    BookController.AddBook(newBook);
                    LoadBooks();
                }
                catch (SecurityException ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
        }

        private void DeleteBook(object sender, RoutedEventArgs e)
        {
            if (BooksBinding.SelectedItems.Count > 0)
            {
                List<Book> selectedBooks = BooksBinding.SelectedItems.Cast<Book>().ToList();
                int[] ids = [.. selectedBooks.Select(s => s.Id)];
                BookController.DeleteBooks(ids);
                LoadBooks();
            }
        }
    }
}
